# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-12 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_choice2_question2_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice2',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question2'),
        ),
    ]
