# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-13 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210512_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice2',
            old_name='timesSelected',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='question2',
            name='numOptions',
        ),
    ]
