# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210513_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='question2',
            name='numChoices',
            field=models.IntegerField(default=4),
        ),
    ]
